#!/usr/bin/env bash
# read, cut and print /etc/passwd

file="/etc/passwd"

while IFS= read -r line; do
	usern=$( echo "$line" | cut -d ":" -f 1 )
	group=$( echo "$line" | cut -d ":" -f 4 )
	home=$( echo "$line" | cut -d ":" -f 6 )
	shell=$( echo "$line" | cut -d ":" -f 7 )
	useridinfo=$( echo "$line" | cut -d ":" -f 5 )
	userid=$( echo "$line" | cut -d ":" -f 3 )
	password=$( echo "$line" | cut -d ":" -f 2 )
	echo "The user $usern is part of the $group gang, lives in $home and rides $shell. $userid's place is protected by the passcode $password, more info about the user here: $useridinfo"
done < "$file"
